### ISSUE TITLE
ECDSA support

### ISSUE THREAD

**Issue by parkan** [libp2p/go-libp2p-crypto#19]
We'd like to be able to natively verify ECDSA signatures (Ethereum). Parallel to https://github.com/libp2p/js-libp2p-crypto/issues/57

@vyzo is on it, just giving you a heads up here

**Comment by vyzo** [comment]
To be more precise, we are interested in the SECP256k1 curve, as used by BTC and ethereum.

**Comment by whyrusleeping** [comment]
@parkan @vyzo  this is merged now, good to close? (Working on bubbling changes up now)

**Comment by parkan** [comment]
🙏
