### ISSUE TITLE
Switch RSA keys from PKCS to OAEP

### ISSUE THREAD

**Issue by arstevens** [libp2p/go-libp2p-crypto#32]
On the go docs for crypto/rsa it states that PKCS should no longer be used and instead OAEP should be used to encrypt plaintext. If this could be changed it would be great. It is a very easy thing to implement.

**Comment by Stebalien** [comment]
That would effectively require adding a new keytype (RSA-OAEP) for backwards compatibility. Ideally, we'd prefer to transition to ed25519 instead (although we can probably just support both).

**Comment by Kubuxu** [comment]
As far as I know, we use the RSA for only signatures. I think we are not using the encryption.

**Comment by raulk** [comment]
We indeed don't use encryption and we've recently removed those APIs: https://github.com/libp2p/go-libp2p-crypto/commit/1f7175219cef61d48a0000a3d15ab6a0b4faf5ee

Thanks @arstevens for the heads-up! Closing this.
