### ISSUE TITLE
protoc version for generating pb/crypto.pb.go

### ISSUE THREAD

**Issue by helinwang** [libp2p/go-libp2p-crypto#33]
Hi,

I am adding a new signature scheme, so I edited `pb/crypto.proto` and have to manually generate `pb/crypto.pb.go`, could you let me know what protoc version should I use to build it?

I tried protoc 3.2.0 but have the following error:
```
$ cd pb
$ make
protoc --gogo_out=. crypto.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: crypto.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
protoc-gen-gogo: program not found or is not executable
--gogo_out: protoc-gen-gogo: Plugin failed with status code 1.
Makefile:7: recipe for target 'crypto.pb.go' failed
make: *** [crypto.pb.go] Error 1
```

**Comment by Stebalien** [comment]
We use the gogo protobuf implementation: https://github.com/gogo/protobuf

**Comment by Stebalien** [comment]
And if we don't answer issues/PRs within a week, please bug us on IRC. We have a ton of repos and issues can slip through the cracks.

**Comment by Stebalien** [comment]
This has been fixed (we now explicitly specify proto2).
