### ISSUE TITLE
IPNS Publishing: crypto/rsa: message too long for RSA public key size 

### ISSUE THREAD

**Issue by kjzz** [libp2p/go-libp2p-crypto#39]
see comment [#5536](https://github.com/ipfs/go-ipfs/issues/5536)

https://github.com/libp2p/go-libp2p-crypto/blob/137c71cdda7aadcaad5eaf03301f7c4f173858e2/rsa.go#L45-L47

**Comment by Stebalien** [comment]
This isn't used by IPNS. However, we *should* probably *document* it: https://github.com/libp2p/go-libp2p-crypto/issues/41
