### ISSUE TITLE
Document size restrictions on Encrypt

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-crypto#41]
See: https://github.com/libp2p/go-libp2p-crypto/issues/39

It's designed to encrypt small things and symmetric keys.

**Comment by raulk** [comment]
We recently [removed this API](https://github.com/libp2p/go-libp2p-crypto/commit/1f7175219cef61d48a0000a3d15ab6a0b4faf5ee), so this issue is now irrelevant.
