### ISSUE TITLE
Why not use golang's ed25519 library?

### ISSUE THREAD

**Issue by ziranliu** [libp2p/go-libp2p-crypto#45]
I noticed you're using github.com/agl/ed25519. But intuitively golang's implementation should be safer and more efficient. Have you thought about using golang.org/x/crypto/ed25519?

**Comment by Stebalien** [comment]
Already fixed :smile:: https://github.com/libp2p/go-libp2p-crypto/issues/17

**Comment by Kubuxu** [comment]
When we started using it it wasn't in the std library (agl is the one who wrote it and now it is in the std lib).
