### ISSUE TITLE
Undefined publick key unmarshall functions

### ISSUE THREAD

**Issue by AlbanWende** [libp2p/go-libp2p-crypto#47]
Greetings from Burkina Faso!

I have an issue that hold me since 5 nights. When I compile or test my project, I get:
..\go-libp2p-crypto\key.go:59:24: undefined: UnmarshalECDSAPublicKey
..\go-libp2p-crypto\key.go:67:24: undefined: UnmarshalECDSAPrivateKey
..\go-libp2p-crypto\key.go:127:10: undefined: GenerateECDSAKeyPair

Can someone help me out? thanks in advance

**Comment by Stebalien** [comment]
Make sure your git repo is clean and up-to-date. It looks like you're missing `ecdsa.go`.

**Comment by AlbanWende** [comment]
You fix it! Thank a lot, a lot, a lot!
