### ISSUE TITLE
Implements missing methods in Key.go

### ISSUE THREAD

**Issue by mushtaqashhar** [libp2p/go-libp2p-crypto#48]
![image](https://user-images.githubusercontent.com/9577601/47604100-65fac580-da12-11e8-91cb-adf5c9480ea8.png)

**Comment by Stebalien** [comment]
You're mixing gx dependencies and non-gx dependencies. You'll need to either run `gx-go rw --fix` in your project to unrewrite the paths or run `gx import github.com/libp2p/go-libp2p-crypto` to import this package into your package.json file.
