### ISSUE TITLE
Key.GenSecret seems pointless

### ISSUE THREAD

**Issue by keks** [libp2p/go-libp2p-crypto#7]
The secret being generated has nothing to do with the Key. Also I have not found anyone use this function. I propose to either completely remove it or to just use it as a package function (i.e. `"github.com/libp2p/go-libp2p-crypto".GenSecret`). However, I don't see much value in reading 16 random bytes - at least not enought to keep it, instead of providing access to `"crypto/rand".Reader`

**Comment by whyrusleeping** [comment]
Yeah... i don't think its used. Probably best to drop it from the package.
