### ISSUE TITLE
Don't allow using one RSA keypair for both encryption and signing

### ISSUE THREAD

**Issue by keks** [libp2p/go-libp2p-crypto#9]
As Kubuxu [pointed out](https://github.com/libp2p/go-libp2p-crypto/issues/8#issuecomment-249827263), this is dangerous. Let's not allow it.

**Comment by whyrusleeping** [comment]
Good note. We've currently (temporarily) dropped the encryption code from the interface, so when we bring that back, we should make sure to have 'modes' on keys to prevent both being used.

**Comment by Kubuxu** [comment]
This isn't huge risk but it is generally recommended against.
So if it is very difficult it doesn't have to happen but should be warned in the docs.

**Comment by keks** [comment]
Does anybody know of a standard for signing encryption keys to say *if you want to send me encrypted messages, use that one*? In OpenPGP these are called *subkeys* and you attach them to your public keys as explained [here](https://tools.ietf.org/html/rfc4880#section-11.1). However I'm not convinced we should incorporate PGP-style key representations...I like the approach though.

**Comment by bigs** [comment]
no longer relevant

**Comment by bigs** [comment]
re-opening because it will become relevant when we bring back this encryption functionality

**Comment by jacobheun** [comment]
We'd like to use the encryption support in js-libp2p to help better support distributed signaling servers, like [webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star/pull/148). We leverage webcrypto in browser, but it rightfully [doesn't support](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#Supported_algorithms) using the same key as signing. We can pull in some large libraries to get around this, but it would be ideal to avoid doing that and start using separate keys.

**Comment by Stebalien** [comment]
Update: I've completely dropped support from RSA keys so we could add (optional) support for OpenSSL (which doesn't support this).

**Comment by Stebalien** [comment]
Fixed.
